### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by littleningmeng** [ennerf/HdrHistogramVisualizer#4]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.641 s
[INFO] Finished at: 2021-06-17T12:42:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hdrhistogram-visualizer: Fatal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by littleningmeng** [comment]
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by ennerf** [comment]
The application was writte pre Java 9 and currently only supports Java 8. I have plans do redo the whole project and create a proper bundle, but I'm not sure what the time line will be on that yet.

For now you'll need to run on Java 8.

**Comment by littleningmeng** [comment]
Thanks a lot
